'use strict';
const programs = [
 {title:'Career Launchpad for Future Leaders',icon:'rocket',tags:'Leadership · Communication · Career Readiness',badge:'Most Popular',color:'#7544c8',bg:'#f3edff',line:'#e2d5fa',duration:'12 weeks',description:'Build the confidence and practical skills to take your first step into the professional world.',modules:['Professional communication and personal branding','Team leadership and problem solving','Portfolio projects and interview preparation']},
 {title:'Tech & Data Accelerator',icon:'cpu',tags:'Data Analytics · Python · AI & ML',badge:'High Demand',color:'#058eb6',bg:'#eaf8ff',line:'#cbeaf7',duration:'Explore track',description:'Turn curiosity about technology into practical skills through guided, hands-on learning.',modules:['Python fundamentals and data analysis','Introduction to artificial intelligence','Build and present a data-driven project']},
 {title:'Design Thinking & Creativity',icon:'lightbulb',tags:'Problem Solving · Innovation · UX Design',badge:'Creative Minds',color:'#d64c83',bg:'#fff0f4',line:'#f9d7e5',duration:'Explore track',description:'Learn to understand people, explore ideas, and create solutions that make a difference.',modules:['User research and creative problem solving','Prototyping and design feedback','Present a human-centered design concept']},
 {title:'Business & Leadership Skills',icon:'users-round',tags:'Communication · Strategy · Teamwork',badge:'Build Leaders',color:'#1b9560',bg:'#eefaf1',line:'#cdeedb',duration:'Explore track',description:'Develop your business mindset and learn how great teams turn ideas into action.',modules:['Business fundamentals and strategic thinking','Team collaboration and communication','Develop and pitch a business proposal']},
 {title:'Digital Marketing & Content Creation',icon:'megaphone',tags:'Social Media · Branding · Content Strategy',badge:'Future Ready',color:'#e77629',bg:'#fff6ec',line:'#f8e0c7',duration:'Explore track',description:'Connect creativity with strategy to build content and campaigns that reach the right audience.',modules:['Brand storytelling and audience research','Content creation and social media planning','Build a campaign portfolio']},
 {title:'Future Skills for Global Careers',icon:'orbit',tags:'Soft Skills · Communication · Global Mindset',badge:'Global Exposure',color:'#6650b7',bg:'#f2efff',line:'#dfd6fa',duration:'Explore track',description:'Build adaptable skills to collaborate confidently in a changing, connected workplace.',modules:['Cross-cultural communication','Adaptability and professional collaboration','Career planning and workplace readiness']}
];
const icons=()=>window.lucide?.createIcons();
const grid=document.querySelector('#program-grid');
const pillColors=[['#6D3FC8','#fff'],['#0A77A0','#fff'],['#F9CFE0','#9B1F52'],['#1A7F4F','#fff'],['#C95515','#fff'],['#DDD5FB','#3B2A8A']];
grid.innerHTML=programs.map((p,i)=>{const [pillBg,pillFg]=pillColors[i];return `<button class="program-card" data-program="${i}" style="--card-color:${p.color};--card-bg:${p.bg};--card-line:${p.line};--pill-bg:${pillBg};--pill-fg:${pillFg}" aria-label="Explore ${p.title}"><span class="program-icon"><i data-lucide="${p.icon}"></i></span><span class="program-title">${p.title}</span><span class="program-tags">${p.tags.split(' · ').map(t=>`<span class="tag">${t}</span>`).join(' <span class="tag-sep" aria-hidden="true">|</span> ')}</span><span class="program-pill">${p.badge}</span></button>`;}).join('');
const stories=[['RS','Riya Sharma','Data Analytics','Upskillab’s hands-on projects and expert mentors helped me gain real industry experience. The program made me confident about my career path.','Ashoka Institute'],['AV','Aman Verma','Full Stack Development','The expert guidance and practical learning helped me build the skills I needed to get placed. It was a game changer for me!','KITE College'],['SK','Sneha Kapoor','Digital Marketing','I loved the industry projects and career support. It really prepared me for the professional world.','KEC College'],['RM','Rahul Mehta','Business & Leadership','Working with a team and presenting our ideas helped me grow into a more confident communicator.','ABS College'],['PS','Priya Singh','Full Stack Development','Building real projects with mentor feedback every week taught me more than any textbook. I now have a portfolio I am proud to show recruiters.','Udai Pratap College'],['AY','Arjun Yadav','Data Analytics','The live case studies made data analysis click for me. The mock interviews gave me the confidence to crack my first internship.','Harish Chandra PG College'],['NG','Neha Gupta','Digital Marketing','Running an actual campaign as part of the program was the best part. I learned how to plan, measure and improve results.','Sunbeam College'],['VP','Vikas Pandey','Business & Leadership','The leadership sessions pushed me out of my comfort zone. Presenting to industry mentors changed how I communicate.','DAV PG College'],['AT','Anjali Tiwari','Career Launchpad','From resume building to interview practice, the career support was personal and practical. I felt prepared at every step.','Agrasen PG College'],['KM','Karan Mishra','Full Stack Development','Team projects and code reviews showed me how real developers work. Upskillab helped me turn my interest into job-ready skills.','Mahatma Gandhi Kashi Vidyapith']];
document.querySelector('#testimonials').innerHTML=stories.map(s=>{const slug=s[1].toLowerCase().replace(/\s+/g,'-');return `<article class="testimonial"><div class="t-photo"><span class="t-initials" aria-hidden="true">${s[0]}</span><img src="assets/testimonials/${slug}.png" alt="${s[1]}" loading="lazy" decoding="async" width="160" height="160" onerror="this.remove()"></div><div class="t-body"><blockquote>“${s[3]}”</blockquote><strong class="t-name">${s[1]}</strong><span class="t-meta">${s[4]||'Ashoka Institute'} <span class="t-sep" aria-hidden="true">|</span> ${s[2]}</span></div></article>`;}).join('');
const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');
function openModal(html){content.innerHTML=html;if(!modal.open)modal.showModal();icons();}
function showProgram(i){const p=programs[i];openModal(`<span class="section-kicker">ASHOKA STUDENT PROGRAM</span><h2>${p.title}</h2><p>${p.description}</p><h3 style="margin-top:20px">What you’ll explore</h3><ul>${p.modules.map(m=>`<li>${m}</li>`).join('')}</ul><p>Includes guided learning, project feedback, and career support. Ask our team for current fees, eligibility, schedules, and availability.</p><button class="btn primary" data-action="call">Discuss this program <i data-lucide="arrow-right"></i></button>`);}
const brochureText=`UPSKILLAB × ASHOKA INSTITUTE\nLearn · Build · Grow\n\nEXCLUSIVE PARTNERSHIP PROGRAM\nA collaboration with Ashoka Institute Student Welfare Wing.\n\nPROGRAMS\n${programs.map((p,i)=>`${i+1}. ${p.title}\n${p.tags}\n${p.description}\n`).join('\n')}\nCAREER LAUNCHPAD\nA flagship 12-week learning program.\n100+ hours of live learning · 8+ industry projects · 1:1 mentor support · Placement assistance.\n\nCONTACT\npartnerships@upskillab.com\n+91 93194 26464\nwww.upskillab.com\n\nPlease confirm fees, eligibility, dates, program details, and availability with the team. Placement assistance is not a placement guarantee. This overview is prepared from the supplied design brief.\n`;
function downloadBrochure(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([brochureText],{type:'text/plain;charset=utf-8'}));a.download='Upskillab-Ashoka-Program-Brochure.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Your program overview has been downloaded.');}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),3500);}
const actions={
 brochure:downloadBrochure,
 call:()=>{openModal('<span class="section-kicker">LET’S TALK ABOUT YOUR FUTURE</span><h2>Book a Free Call</h2><p>Share a few details and send a callback request to the Upskillab partnerships team.</p><form id="call-form"><label for="name">Your name</label><input id="name" name="name" autocomplete="name" required maxlength="80"><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" required><label for="phone">Phone number</label><input id="phone" name="phone" type="tel" autocomplete="tel" required pattern="[+0-9 ()-]{7,20}"><button class="btn primary" type="submit">Continue to email <i data-lucide="arrow-up-right"></i></button><p style="font-size:13px;margin-top:12px">This opens your email app. Your request is sent only when you send that email. No details are stored on this website.</p></form>');document.querySelector('#call-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);const body=`Hello Upskillab,\nI would like a free career guidance call.\n\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nPhone: ${d.get('phone')}\nInstitute: Ashoka Institute\n\nPlease share available times. Thank you.`;window.location.href=`mailto:partnerships@upskillab.com?subject=${encodeURIComponent('Ashoka student — Free call request')}&body=${encodeURIComponent(body)}`;});},
 login:()=>openModal('<span class="section-kicker">STUDENT ACCESS</span><h2>Already learning with us?</h2><p>A student portal link has not been configured for this site yet. Contact the team for help accessing your learning account.</p><a class="btn primary" href="mailto:partnerships@upskillab.com?subject=Student%20login%20support">Contact student support <i data-lucide="mail"></i></a>'),
 resources:()=>openModal('<span class="section-kicker">YOUR NEXT STEP, MADE CLEARER</span><h2>Student Resources</h2><p>Explore the program overview, compare learning tracks, or speak with a career mentor.</p><button class="search-result" data-action="brochure">Download the program overview ↓</button><button class="search-result" data-action="search">Find a program →</button><button class="search-result" data-action="call">Request career guidance →</button>'),
 search:()=>{openModal('<h2>Find your program</h2><label for="program-search">Search a skill or program</label><input id="program-search" type="search" placeholder="Try Python, leadership, or design"><div id="search-results"></div>');const input=document.querySelector('#program-search');const render=()=>{const matches=programs.map((p,i)=>({...p,i})).filter(p=>(p.title+' '+p.tags).toLowerCase().includes(input.value.toLowerCase().trim()));document.querySelector('#search-results').innerHTML=matches.length?matches.map(p=>`<button class="search-result" data-program="${p.i}">${p.title} →</button>`).join(''):'<p style="margin-top:16px">No matching programs. Try a different skill or contact the team.</p>';};input.addEventListener('input',render);render();input.focus();},
 privacy:()=>openModal('<h2>Privacy information</h2><p>This static website does not store callback form details or use analytics. The callback action opens your email app so you can choose whether to send your information to Upskillab.</p><p style="margin-top:12px">Fonts and interface libraries are loaded from third-party providers, which receive standard web request information. Contact partnerships@upskillab.com for privacy questions.</p><p style="margin-top:12px">This is a website implementation notice. An organization-approved privacy policy should be supplied before public launch.</p>'),
 terms:()=>openModal('<h2>Program information & terms</h2><p>Program descriptions are based on the supplied partnership brief. Confirm fees, admission requirements, schedules, and availability with the Upskillab team before enrolling. Placement support does not guarantee employment.</p><p style="margin-top:12px">The student stories shown are illustrative. Official enrollment terms and policies should be supplied by the organization before public launch.</p>')
};
document.addEventListener('click',e=>{const p=e.target.closest('[data-program]');if(p){showProgram(Number(p.dataset.program));return;}const a=e.target.closest('[data-action]');if(a)actions[a.dataset.action]?.();});
document.querySelector('#close-modal').addEventListener('click',()=>modal.close());
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
const menu=document.querySelector('#menu-toggle');menu.addEventListener('click',()=>{const open=document.querySelector('#navigation').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
document.querySelectorAll('nav a,nav button').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#navigation').classList.remove('open');menu.setAttribute('aria-expanded','false');}));
const track=document.querySelector('#testimonials');function slide(direction){const step=track.querySelector('.testimonial').getBoundingClientRect().width+18;const max=track.scrollWidth-track.clientWidth;let left=track.scrollLeft+direction*step;if(left>max+5)left=0;if(left< -5)left=max;track.scrollTo({left,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
document.querySelector('#next-story').addEventListener('click',()=>slide(1));document.querySelector('#prev-story').addEventListener('click',()=>slide(-1));
document.querySelector('#view-programs').addEventListener('click',()=>{document.querySelector('#program-grid').scrollIntoView({block:'start'});grid.querySelector('button').focus({preventScroll:true});});
document.querySelector('#year').textContent=new Date().getFullYear();icons();
